import { StrictMode } from 'react'
import { createRoot } from 'react-dom/client'
import './index.css'
import App from './App.jsx'
import Header from './components/Header/Header.jsx'

createRoot(document.getElementById('root')).render(
  <StrictMode>
    <Header />
    <div>asd</div>
    <div>asd</div>
    <div>asd</div>
    <div>asd</div>
    <div>asd</div>
    <div>asd</div>
    <div>asd</div>
    <div>asd</div>
    <div>asd</div>
    <div>asd</div>
    <div>asd</div>
    <div>asd</div>
    <div>asd</div>
    <div>asd</div>
    <div>asd</div>
    <div>asd</div>
    <div>asd</div>
    <div>asd</div>
    <div>asd</div>
    <div>asd</div>
    <div>asd</div>
    <div>asd</div>
    <div>asd</div>
    <div>asd</div>
    <div>asd</div>
    <div>asd</div>
    <div>asd</div>
    <div>asd</div>
    <div>asd</div>
    <div>asd</div>
    <div>asd</div>
    <div>asd</div>
    <div>asd</div>
    <div>asd</div>
    <div>asd</div>
    <div>asd</div>
    <div>asd</div>
    <div>asd</div>
    <div>asd</div>
    <div>asd</div>
    <div>asd</div>
    <div>asd</div>
    <div>asd</div>
    <div>asd</div>
    <div>asd</div>
    <div>asd</div>
    <div>asd</div>
    <div>asd</div>
    <div>asd</div>
    <div>asd</div>
    <div>asd</div>
    <div>asd</div>
    <div>asd</div>
    <div>asd</div>
    <div>asd</div>
    <div>asd</div>
    <div>asd</div>
    <div>asd</div>
    <div>asd</div>
    <div>asd</div>
    <div>asd</div>
    <div>asd</div>
    <div>asd</div>
    <div>asd</div>
    <div>asd</div>
    <div>asd</div>
    <div>asd</div>
    <div>asd</div>
    <div>asd</div>
    <div>asd</div>
    <div>asd</div>
    <div>asd</div>
    <div>asd</div>
    <div>asd</div>
    <div>asd</div>
    <div>asd</div>
    <div>asd</div>
    <div>asd</div>
    <div>asd</div>
    <div>asd</div>
    <div>asd</div>
    <div>asd</div>
    <div>asd</div>
    <div>asd</div>
    <div>asd</div>
    <div>asd</div>
    <div>asd</div>
    <div>asd</div>
    <div>asd</div>
    <div>asd</div>
    <div>asd</div>
    <div>asd</div>
    <div>asd</div>
    <div>asd</div>
    <div>asd</div>
    <div>asd</div>
    <div>asd</div>
    <div>asd</div>
    <div>asd</div>
    <div>asd</div>
    <div>asd</div>
    <div>asd</div>
    <div>asd</div>
    <div>asd</div>
    <div>asd</div>
    <div>asd</div>
    <div>asd</div>
    <div>asd</div>
    <div>asd</div>
    <div>asd</div>
    <div>asd</div>
    <div>asd</div>
    <div>asd</div>
    <div>asd</div>
    <div>asd</div>
    <div>asd</div>
    <div>asd</div>
    <div>asd</div>
    <div>asd</div>
    <div>asd</div>
    <App />
  </StrictMode>,
)
